### ISSUE TITLE
No available formula with the name "eigenpy-python3"

### ISSUE THREAD

**Issue by ialong** [stack-of-tasks/pinocchio#1082]
Running `brew install pinocchio` currently fails due to eigenpy now using python3 by default (there is no `eigenpy-python3` formula anymore).

This is the output:

```❯ brew install pinocchio
==> Installing pinocchio from gepetto/gepetto
Error: No available formula with the name "eigenpy-python3" (dependency of gepetto/gepetto/pinocchio)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.```

**Comment by jcarpent** [comment]
@ialong I'm currently regenerating the images. In 10 minutes, it should be available.

**Comment by ialong** [comment]
great thanks! (amazing response speed :))

**Comment by jcarpent** [comment]
Done! The binaries are now available.
Best,
Justin

**Comment by ialong** [comment]
It seems I'm still getting the same issue (after running brew update)...

**Comment by jcarpent** [comment]
I would advise you to proceed as follows:
```
brew untap gepetto/geptto
brew tap gepetto/geptto
brew install pinocchio
```
or, for Python 2:
```
brew install pinocchio@2
```

**Comment by ialong** [comment]
@jcarpent unfortunately still the same error.

**Comment by jcarpent** [comment]
OK. I've found the bug.

**Comment by jcarpent** [comment]
I just need 5 mins to solve it and regenerate the correct image

**Comment by jcarpent** [comment]
Done. Thanks @ialong for your quick feedback.

**Comment by ialong** [comment]
It worked! @jcarpent thank you very much for fixing this so quickly

**Comment by jcarpent** [comment]
You're welcome.
