### ISSUE TITLE
MeshLoader inconsistency on import  switching 

### ISSUE THREAD

**Issue by rstrudel** [stack-of-tasks/pinocchio#1133]
Hello,

Depending on the order of import, instances of `MeshLoader` have differents methods. To reproduce, you can do:

code 1:
```
import hppfcl 
import pinocchio as pin 
meshloader = hppfcl.MeshLoader() 
print(dir(meshloader)) 
```
result:
```
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'create']
```
code 2:
```
import pinocchio as pin 
import hppfcl
meshloader = hppfcl.MeshLoader() 
print(dir(meshloader)) 
```
result:
```
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'load']
```

Notice the `create` method in first case and the `load` method in the second case. This bug seens related to the interaction between pinocchio and hppfcl, it seems appropriate to also tag @jmirabel .

**Comment by jmirabel** [comment]
I encountered this some time ago and I believe I solved it. Which version do you use ?

**Comment by jmirabel** [comment]
#1084 should have solved this.

**Comment by rstrudel** [comment]
I am using (pinocchio 2.3.1)[https://anaconda.org/conda-forge/pinocchio] and (hpp-fcl 1.3.0) [https://anaconda.org/conda-forge/hpp-fcl] which are the latest versions available on conda-forge.

**Comment by jmirabel** [comment]
I checked and there hasn't been any release since the fix. The bindings you should use are the one from hppfcl so you should import pinocchio before hppfcl.

**Comment by rstrudel** [comment]
Yes, that is what I've been doing for a while. I checked today if things have changed and as it has not I opened this issue so that there is a trace of this problem somewhere.

**Comment by jcarpent** [comment]
As mentioned by @jmirabel, this issue has been solved in #1084. I will close it as no action is no more required.

**Comment by rstrudel** [comment]
As there is no release, this is still a problem you will run into with the available packages. I opened it because I was not the only one to run into the problem.
