### ISSUE TITLE
Support for Arch Linux (eigen 5)?

### ISSUE THREAD

**Issue by costashatz** [stack-of-tasks/pinocchio#2778]
Hello all,

I am trying to install pinocchio on an Arch Linux setup, but I am getting many eigen-related errors (I tried both through the AUR package, and on my own). A few examples:

- `error: ‘EIGEN_NOEXCEPT’ does not name a type [-Wtemplate-body]`
- `error: ISO C++ forbids declaration of ‘EIGEN_EMPTY_STRUCT_CTOR’ with no type [-Wtemplate-body]`

And many other similar ones. After careful examination, I think the issue is that in Arch Linux, eigen is on version 5 (see [here](https://archlinux.org/packages/extra/x86_64/eigen/)). Is this the case? If yes, what's the status and support for this?

Or maybe it is something else?

Thanks in advance!

**Comment by nim65s** [comment]
Ah, yes, Arch did update eigen to v5. And yes, we are not ready for it.
I guess the good solution here would be to downgrade eigen to v3.4.1. 
And I just saw https://aur.archlinux.org/packages/eigen3. Let me try to update the AUR package with that

**Comment by nim65s** [comment]
@costashatz : the AUR packaging should be fixed. Can you try again ?

Also, ref. ongoing upgrade to eigen 5 in https://github.com/stack-of-tasks/eigenpy/pull/596

**Comment by costashatz** [comment]
Still fails. I think it auto-detects `eigen 5` in the CMake, because I am getting exactly the same errors as before (cleaned cache etc).

**Comment by nim65s** [comment]
In that case I guess you need to build in an isolated environment without eigen (5) and only eigen3. Or try with `sudo pacman -Rcsn eigen`, but this may have consequences 😅

**Comment by costashatz** [comment]
Can't I pass path for Eigen to pinocchio's CMake?

**Comment by nim65s** [comment]
Yes, `-DEigen3_ROOT=/opt/eigen3` should work

**Comment by costashatz** [comment]
This worked. I think the AUR package should include this until you actually provide support for Eigen 5. Thanks!

**Comment by nim65s** [comment]
Ok, this is pushed :)
